### ISSUE TITLE
Problem with video and audio

### ISSUE THREAD

**Issue by hoangthanh49** [android-rpi/device_arpi_rpi4#11]
Hi all

My rpi4 can boot normally with built image from this source.
But when I tried to play video file (mp4) by vlc or any other video app, it can not and show black screen.
And about audio, don't have sound although audio file can play normally (mp3 file)

Any one can support this issue?

Thanks so much

**Comment by peyo-hd** [comment]
Audio/Video playback is not yet supported.
Waiting for contribution on these area.

**Comment by hoangthanh49** [comment]
Hello peyo

Video can play now although unstable.
But audio still no sound.
Are you working on it or has any suggestion to check?
