### ISSUE TITLE
ADB support

### ISSUE THREAD

**Issue by lohriialo** [android-rpi/device_arpi_rpi4#27]
I've tried using a `usb-a to usb-c cable` on all the usb ports but `./adb devices` doesn't list anything. I'm trying to install some apks for testing

**Comment by lohriialo** [comment]
I've tried using a `usb-a to usb-c` cable on all the usb ports but `./adb devices` doesn't list anything. I'm trying to install some apks for testing

**Comment by peyo-hd** [comment]
https://github.com/android-rpi/device_arpi_rpi4/wiki

**Comment by lohriialo** [comment]
Thanks @peyo-hd got it working now!
Because it's currently running TvSetting, IP is under Settings ->Device Preferences ->About ->Status
