### ISSUE TITLE
when turn wifi on, it reboots in few seconds! Debug Msg are here

### ISSUE THREAD

**Issue by andersling** [android-rpi/device_arpi_rpi4#32]
Hi,All! When turn on WiFi ,the room keep rebooting and rebooting, i catch the debug messages from USB ,please take a look at it,thanks!

[ 35.187724] type=1400 audit(1597320517.289:101): avc: denied { write } for comm="main" name="tasks" dev="tmpfs" ino=10663 scontext=u:r:zygote:s0 tcontext=u:object_r:device:s0 tclass=file permissive=1
[ 35.200637] init: Could not find 'vendor.lineage.livedisplay@2.0::IAutoContrast/default' for ctl.interface_start
[ 35.219864] type=1400 audit(1597320517.289:101): avc: denied { write } for comm="main" name="tasks" dev="tmpfs" ino=10663 scontext=u:r:zygote:s0 tcontext=u:object_r:device:s0 tclass=file permissive=1
[ 35.230787] init: Received control message 'interface_start' for 'vendor.lineage.livedisplay@2.0::IDisplayColorCalibration/default' from pid: 146 (/system/bin/hwservicemanager)
[ 35.247169] type=1400 audit(1597320517.289:102): avc: denied { open } for comm="main" path="/dev/stune/foreground/tasks" dev="tmpfs" ino=10663 scontext=u:r:zygote:s0 tcontext=u:object_r:device:s0 tclass=file permissive=1
[ 35.263288] init: Could not find 'vendor.lineage.livedisplay@2.0::IDisplayColorCalibration/default' for ctl.interface_start
[ 35.294351] init: Received control message 'interface_start' for 'vendor.lineage.livedisplay@2.0::IDisplayModes/default' from pid: 146 (/system/bin/hwservicemanager)
[ 35.309852] init: Could not find 'vendor.lineage.livedisplay@2.0::IDisplayModes/default' for ctl.interface_start
[ 35.320421] init: Received control message 'interface_start' for 'vendor.lineage.livedisplay@2.0::IReadingEnhancement/default' from pid: 146 (/system/bin/hwservicemanager)
[ 36.851865] type=1400 audit(1597320517.289:102): avc: denied { open } for comm="main" path="/dev/stune/foreground/tasks" dev="tmpfs" ino=10663 scontext=u:r:zygote:s0 tcontext=u:object_r:device:s0 tclass=file permissive=1
[ 36.873786] type=1400 audit(1597320518.979:103): avc: denied { write } for comm="main" name="tasks" dev="tmpfs" ino=731 scontext=u:r:zygote:s0 tcontext=u:object_r:device:s0 tclass=file permissive=1
[ 36.894704] type=1400 audit(1597320518.979:103): avc: denied { write } for comm="main" name="tasks" dev="tmpfs" ino=731 scontext=u:r:zygote:s0 tcontext=u:object_r:device:s0 tclass=file permissive=1
[ 36.915905] type=1400 audit(1597320518.979:104): avc: denied { open } for comm="main" path="/dev/stune/top-app/tasks" dev="tmpfs" ino=731 scontext=u:r:zygote:s0 tcontext=u:object_r:device:s0 tclass=file permissive=1
[ 37.175658] type=1400 audit(1597320518.979:104): avc: denied { open } for comm="main" path="/dev/stune/top-app/tasks" dev="tmpfs" ino=731 scontext=u:r:zygote:s0 tcontext=u:object_r:device:s0 tclass=file permissive=1
[ 37.198532] type=1400 audit(1597320519.309:105): avc: denied { write } for comm="main" name="tasks" dev="tmpfs" ino=10663 scontext=u:r:zygote:s0 tcontext=u:object_r:device:s0 tclass=file permissive=1 app=com.android.providers.media
[ 37.670057] 8<--- cut here ---
[ 37.674677] Unable to handle kernel NULL pointer dereference at virtual address 00000ef8
[ 37.683157] pgd = 1377b4d8
[ 37.685908] [00000ef8] *pgd=13294003, *pmd=00000000
[ 37.690882] Internal error: Oops: 206 [#1] PREEMPT SMP ARM
[ 37.696454] Modules linked in:
[ 37.699562] CPU: 2 PID: 683 Comm: wpa_supplicant Not tainted 5.4.58-v7l-g6c0b7b018b84 #1
[ 37.707772] Hardware name: BCM2711
[ 37.711246] PC is at brcmf_p2p_send_action_frame+0x3e8/0x9c0
[ 37.716994] LR is at brcmf_p2p_send_action_frame+0x19c/0x9c0
[ 37.722740] pc : [] lr : [] psr: 20010013
[ 37.729108] sp : d432fad0 ip : 00000000 fp : d432fb24
[ 37.734414] r10: 00000000 r9 : ffffffff r8 : 00000000
[ 37.739720] r7 : d3c68800 r6 : 00000001 r5 : d4f0a80c r4 : d4f0a800
[ 37.746345] r3 : 00000400 r2 : 00000000 r1 : 00000006 r0 : 00000000
[ 37.752965] Flags: nzCv IRQs on FIQs on Mode SVC_32 ISA ARM Segment user
[ 37.760212] Control: 30c5383d Table: 13a2a740 DAC: 55555555
[ 37.766041] Process wpa_supplicant (pid: 683, stack limit = 0xf9b8e57a)
[ 37.772745] Stack: (0xd432fad0 to 0xd4330000)
[ 37.777159] fac0: 00000304 c04356b8 d432fb24 d432fae8
[ 37.785459] fae0: ef803540 c043599c d432fb88 d4fb0620 d4f0b640 00000000 d432fb24 c1806448
[ 37.793759] fb00: d41aac34 d432fbb8 d4f0a800 0000002f 00000017 d3c68800 d432fb74 d432fb28
[ 37.802057] fb20: c08e1d0c c08eba8c 00000000 00000000 00000017 00000985 d4fb0620 d4ea1008
[ 37.810350] fb40: 00000985 5cac72ff d432fb84 d41aac34 d4ea1008 d432fbe4 d4fb0280 d432fbb8
[ 37.818643] fb60: d4fb0000 d3a70014 d432fbac d432fb78 c0e597e4 c08e1b64 d432fbac d432fb88
[ 37.826941] fb80: c0c6ddac d432fc74 c1806448 d4fb0000 d4ea1008 00000000 d49e9300 d3a70014
[ 37.835242] fba0: d432fc34 d432fbb0 c0e4ee60 c0e596dc 00000000 0000003b 00000000 00000000
[ 37.843536] fbc0: c115ec34 00000000 c10396f8 d4f06d18 00000000 00000985 00000000 00000000
[ 37.851827] fbe0: 00000000 d4f06d18 00000001 000003e8 d41aac34 0000002f 00000000 00000000
[ 37.860126] fc00: 00000000 5cac72ff c070cf24 c115fba0 c1412e80 d41aac14 c1806448 d49e9000
[ 37.868417] fc20: 00000000 c1895ec0 d432fccc d432fc38 c0c6ea64 c0e4ebf0 c115ea9c 00000000
[ 37.876716] fc40: d432fcd4 00000004 c196e258 00000014 d3c6b000 d432fcd4 d432fcdc d432fc68
[ 37.885017] fc60: c065488c c02b1dc0 d39ce000 d3348d30 00000164 5f352d63 570002ab d41aac00
[ 37.893318] fc80: d41aac10 d41aac14 d3c6b000 c1895ec0 d4fb0000 d4ea1008 d432fcd4 5cac72ff
[ 37.901611] fca0: efa50980 00000000 c1806448 c0c6e7e0 d49e9000 d41aac00 00000000 efb57800
[ 37.909902] fcc0: d432fd1c d432fcd0 c0c6d774 c0c6e7ec 032c0000 00000000 00000000 00000000
[ 37.918194] fce0: 00000000 00000000 00000000 00000000 00000000 5cac72ff 00000000 c189ab50
[ 37.926492] fd00: d49e9000 efb57864 00000064 c1895ec0 d432fd34 d432fd20 c0c6de40 c0c6d688
[ 37.934792] fd20: efa08240 d49e9000 d432fd74 d432fd38 c0c6ce70 c0c6de18 00000000 c1806448
[ 37.943084] fd40: 7fffffff 5cac72ff d432fd74 c1806448 d49e9000 d3823c00 00000000 00000000
[ 37.951375] fd60: d432ff4c 00000000 d432fde4 d432fd78 c0c6d1e0 c0c6cc88 00000000 00000000
[ 37.959668] fd80: 00000000 00000000 00000000 00000000 d41aac00 00000064 c14124e0 d42db7c0
[ 37.967965] fda0: 00000000 000002ab 000003f2 000003f2 00000000 5cac72ff d432fde4 d432ff4c
[ 37.976261] fdc0: 00000000 00000000 c1806448 d432fdf4 d4701080 00000000 d432fe44 d432fde8
[ 37.984554] fde0: c0bdcf80 c0c6cf0c d432e000 00000000 d432fe44 d432fe00 c0bdd1cc c06e2760
[ 37.992845] fe00: d432fe50 d432ff54 b3335cf4 0000000c beff7410 5cac72ff 00000000 c1806448
[ 38.001135] fe20: d432ff4c 00000000 d4701080 00000000 d432e000 00000128 d432ff3c d432fe48
[ 38.009428] fe40: c0bdd2cc c0bdcda0 00000000 c06547fc 00000000 b3346000 00000064 c0bdcbac
[ 38.017719] fe60: 00008000 00000000 d432fe80 5cac72ff 00039e7e 00000000 ffffffff 00000001
[ 38.026011] fe80: 00000000 5cac72ff c0bdcbac c1806448 d31e9f00 00000010 00000000 00000000
[ 38.034302] fea0: d4701080 00000126 d432ff24 c03a11c4 c1940ca8 c1806448 c181c110 d432ff68
[ 38.042594] fec0: d3823c00 beff7468 d432ff64 00000001 d432ff54 d432fee0 c03a11c4 c02b1dc0
[ 38.050886] fee0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 38.059177] ff00: d432ff70 d432ff6c d3823c00 00000000 00000000 5cac72ff 0000000a c1806448
[ 38.067468] ff20: beff7418 d4701080 00000000 00000000 d432ffa4 d432ff40 c0bdecb4 c0bdd25c
[ 38.075760] ff40: 00000000 00000000 d432ffa4 d432fe94 0000000c 00000005 00000000 00000000
[ 38.084051] ff60: d432fe5c 00000000 0000000a 00000000 00000000 00000000 00000000 5cac72ff
[ 38.092342] ff80: b3346063 beff7418 00000000 b3335c40 00000128 c02011c4 00000000 d432ffa8
[ 38.100633] ffa0: c0201000 c0bdec0c beff7418 00000000 00000007 beff7418 00000000 beff7468
[ 38.108925] ffc0: beff7418 00000000 b3335c40 00000128 0c278835 b3335c40 b3cba260 beff74a8
[ 38.117217] ffe0: b334e200 beff73f8 b36712cb b3c9aef0 40010010 00000007 00000000 00000000
[ 38.125507] Backtrace:
[ 38.127989] [] (brcmf_p2p_send_action_frame) from [] (brcmf_cfg80211_mgmt_tx+0x1b4/0x2c0)
[ 38.138046] r10:d3c68800 r9:00000017 r8:0000002f r7:d4f0a800 r6:d432fbb8 r5:d41aac34
[ 38.145983] r4:c1806448
[ 38.148553] [] (brcmf_cfg80211_mgmt_tx) from [] (cfg80211_mlme_mgmt_tx+0x114/0x3c8)
[ 38.158079] r10:d3a70014 r9:d4fb0000 r8:d432fbb8 r7:d4fb0280 r6:d432fbe4 r5:d4ea1008
[ 38.166017] r4:d41aac34
[ 38.168584] [] (cfg80211_mlme_mgmt_tx) from [] (nl80211_tx_mgmt+0x27c/0x3a4)
[ 38.177493] r10:d3a70014 r9:d49e9300 r8:00000000 r7:d4ea1008 r6:d4fb0000 r5:c1806448
[ 38.185431] r4:d432fc74
[ 38.187998] [] (nl80211_tx_mgmt) from [] (genl_rcv_msg+0x284/0x4d8)
[ 38.196114] r10:c1895ec0 r9:00000000 r8:d49e9000 r7:c1806448 r6:d41aac14 r5:c1412e80
[ 38.204052] r4:c115fba0
[ 38.206618] [] (genl_rcv_msg) from [] (netlink_rcv_skb+0xf8/0x12c)
[ 38.214645] r10:efb57800 r9:00000000 r8:d41aac00 r7:d49e9000 r6:c0c6e7e0 r5:c1806448
[ 38.222582] r4:00000000
[ 38.225148] [] (netlink_rcv_skb) from [] (genl_rcv+0x34/0x44)
[ 38.232735] r8:c1895ec0 r7:00000064 r6:efb57864 r5:d49e9000 r4:c189ab50
[ 38.239531] [] (genl_rcv) from [] (netlink_unicast+0x1f4/0x284)
[ 38.247293] r5:d49e9000 r4:efa08240
[ 38.250916] [] (netlink_unicast) from [] (netlink_sendmsg+0x2e0/0x3f8)
[ 38.259296] r10:00000000 r9:d432ff4c r8:00000000 r7:00000000 r6:d3823c00 r5:d49e9000
[ 38.267233] r4:c1806448
[ 38.269799] [] (netlink_sendmsg) from [] (____sys_sendmsg+0x1ec/0x250)
[ 38.278179] r10:00000000 r9:d4701080 r8:d432fdf4 r7:c1806448 r6:00000000 r5:00000000
[ 38.286116] r4:d432ff4c
[ 38.288681] [] (____sys_sendmsg) from [] (___sys_sendmsg+0x7c/0xa8)
[ 38.296797] r10:00000128 r9:d432e000 r8:00000000 r7:d4701080 r6:00000000 r5:d432ff4c
[ 38.304734] r4:c1806448
[ 38.307298] [] (___sys_sendmsg) from [] (sys_sendmsg+0xb4/0xe0)
[ 38.315061] r8:00000000 r7:00000000 r6:d4701080 r5:beff7418 r4:c1806448
[ 38.321858] [] (sys_sendmsg) from [] (ret_fast_syscall+0x0/0x28)
[ 38.329709] Exception stack(0xd432ffa8 to 0xd432fff0)
[ 38.334827] ffa0: beff7418 00000000 00000007 beff7418 00000000 beff7468
[ 38.343118] ffc0: beff7418 00000000 b3335c40 00000128 0c278835 b3335c40 b3cba260 beff74a8
[ 38.351409] ffe0: b334e200 beff73f8 b36712cb b3c9aef0
[ 38.356527] r8:c02011c4 r7:00000128 r6:b3335c40 r5:00000000 r4:beff7418
[ 38.363322] Code: e3a06001 e5c43119 eaffffca e5942024 (e5922ef8)
[ 38.392961] ---[ end trace fc639dc6ca8b59a2 ]---
[ 38.408325] Kernel panic - not syncing: Fatal exception
[ 38.413643] CPU1: stopping
[ 38.416389] CPU: 1 PID: 200 Comm: main Tainted: G D 5.4.58-v7l-g6c0b7b018b84 #1
[ 38.425121] Hardware name: BCM2711
[ 38.428564] Backtrace:
[ 38.431048] [] (dump_backtrace) from [] (show_stack+0x20/0x24)
[ 38.438724] r6:00000000 r5:c18a9a0c r4:60070193 r3:5cac72ff
[ 38.444462] [] (show_stack) from [] (dump_stack+0xd0/0x114)
[ 38.451875] [] (dump_stack) from [] (handle_IPI+0x3a8/0x424)
[ 38.459373] r9:c1806bb4 r8:f0815000 r7:00000001 r6:c18bef60 r5:c16c2950 r4:00000004
[ 38.467225] [] (handle_IPI) from [] (gic_handle_irq+0x84/0x88)
[ 38.474900] r10:d1cc3044 r9:d391a000 r8:f0815000 r7:f0814000 r6:d391bd38 r5:f081400c
[ 38.482838] r4:c1806ef4
[ 38.485401] [] (gic_handle_irq) from [] (__irq_svc+0x5c/0x94)
[ 38.492986] Exception stack(0xd391bd38 to 0xd391bd80)
[ 38.498104] bd20: d1cbe380 d40a8f40
[ 38.506396] bd40: d40bd454 d40bd450 00000002 00000001 d1cc3000 d40a8f18 d1cbe388 d40a8f18
[ 38.514687] bd60: d1cc3044 d391bd9c d40c2480 d391bd88 00000002 c03f9acc 80070013 ffffffff
[ 38.522979] r8:d1cbe388 r7:d391bd6c r6:ffffffff r5:80070013 r4:c03f9acc r3:00000002
[ 38.530833] [] (anon_vma_interval_tree_insert) from [] (anon_vma_clone+0xf0/0x1f8)
[ 38.540269] r5:d40d6160 r4:d1cbe380
[ 38.543889] [] (anon_vma_clone) from [] (anon_vma_fork+0x34/0x14c)
[ 38.551916] r10:d1cbff40 r9:d1cbff30 r8:d4646f40 r7:d1cc3000 r6:d3e29c00 r5:d3833480
[ 38.559854] r4:d1cc3000
[ 38.562419] [] (anon_vma_fork) from [] (dup_mm+0x3c8/0x4b8)
[ 38.569829] r9:d1cbff30 r8:d4646f40 r7:d1cc3000 r6:d3e29c00 r5:d3833480 r4:00000001
[ 38.577681] [] (dup_mm) from [] (copy_process+0x153c/0x18f4)
[ 38.585179] r10:d1c914bc r9:00000000 r8:01200000 r7:d4b2e800 r6:d1c91040 r5:00000000
[ 38.593115] r4:d4e2f5b8
[ 38.595681] [] (copy_process) from [] (_do_fork+0x9c/0x424)
[ 38.603092] r10:00000078 r9:d391bf58 r8:00000000 r7:c1806448 r6:5cac72ff r5:b12cddc8
[ 38.611028] r4:c1806448
[ 38.613594] [] (_do_fork) from [] (sys_clone+0xa0/0xa8)
[ 38.620652] r10:00000078 r9:d391a000 r8:c02011c4 r7:00000078 r6:5cac72ff r5:b12cddc8
[ 38.628589] r4:c1806448
[ 38.631154] [] (sys_clone) from [] (ret_fast_syscall+0x0/0x28)
[ 38.638826] Exception stack(0xd391bfa8 to 0xd391bff0)
[ 38.643944] bfa0: b12cddc8 00000001 01200011 00000000 00000000 00000000
[ 38.652235] bfc0: b12cddc8 00000001 be969954 00000078 000000c8 000000c8 af589260 b0e92140
[ 38.660526] bfe0: be969918 be969908 af5327db af52c7cc
[ 38.665644] r6:be969954 r5:00000001 r4:b12cddc8
[ 38.670322] CPU2: stopping
[ 38.673064] CPU: 2 PID: 1181 Comm: Jit thread pool Tainted: G D 5.4.58-v7l-g6c0b7b018b84 #1
[ 38.682854] Hardware name: BCM2711
[ 38.686296] Backtrace:
[ 38.688775] [] (dump_backtrace) from [] (show_stack+0x20/0x24)
[ 38.696450] r6:00000000 r5:c18a9a0c r4:600d0193 r3:5cac72ff
[ 38.702187] [] (show_stack) from [] (dump_stack+0xd0/0x114)
[ 38.709600] [] (dump_stack) from [] (handle_IPI+0x3a8/0x424)
[ 38.717097] r9:c1806bb4 r8:f0815000 r7:00000002 r6:c18bef60 r5:c16c2950 r4:00000004
[ 38.724950] [] (handle_IPI) from [] (gic_handle_irq+0x84/0x88)
[ 38.732625] r10:a4c2f368 r9:00000017 r8:f0815000 r7:f0814000 r6:d26c3fb0 r5:f081400c
[ 38.740561] r4:c1806ef4
[ 38.743125] [] (gic_handle_irq) from [] (__irq_usr+0x4c/0x60)
[ 38.750710] Exception stack(0xd26c3fb0 to 0xd26c3ff8)
[ 38.755829] 3fa0: a4cb78f0 a4cb7480 a4cb7398 00000006
[ 38.764121] 3fc0: a4ca8eb0 a4cb7040 a4ca8ed4 00000006 00000000 00000017 a4c2f368 a4cb77a8
[ 38.772412] 3fe0: 00000000 9ec043d8 a31c0ced a31c0d90 200d0030 ffffffff
[ 38.779117] r8:30c5387d r7:30c5383d r6:ffffffff r5:200d0030 r4:a31c0d90 r3:a4cb78f0
[ 38.786967] CPU0: stopping
[ 38.789709] CPU: 0 PID: 231 Comm: surfaceflinger Tainted: G D 5.4.58-v7l-g6c0b7b018b84 #1
[ 38.799321] Hardware name: BCM2711
[ 38.802764] Backtrace:
[ 38.805242] [] (dump_backtrace) from [] (show_stack+0x20/0x24)
[ 38.812917] r6:00000000 r5:c18a9a0c r4:600f0193 r3:5cac72ff
[ 38.818653] [] (show_stack) from [] (dump_stack+0xd0/0x114)
[ 38.826064] [] (dump_stack) from [] (handle_IPI+0x3a8/0x424)
[ 38.833563] r9:c1806bb4 r8:f0815000 r7:00000000 r6:c18bef60 r5:c16c2950 r4:00000004
[ 38.841415] [] (handle_IPI) from [] (gic_handle_irq+0x84/0x88)
[ 38.849089] r10:00000000 r9:b06df810 r8:f0815000 r7:f0814000 r6:d3e27fb0 r5:f081400c
[ 38.857027] r4:c1806ef4
[ 38.859591] [] (gic_handle_irq) from [] (__irq_usr+0x4c/0x60)
[ 38.867176] Exception stack(0xd3e27fb0 to 0xd3e27ff8)
[ 38.872295] 7fa0: 00000004 00000003 00000000 00000003
[ 38.880587] 7fc0: b06a91a0 b06df928 b061d6f8 00000000 b06dfb04 b06df810 00000000 b2621668
[ 38.888878] 7fe0: b26e07bc bef21e18 b26492c9 b2e58eba 600f0030 ffffffff
[ 38.895583] r8:30c5387d r7:30c5383d r6:ffffffff r5:600f0030 r4:b2e58eba r3:00000004
[ 38.903444] Rebooting in 5 seconds..
-----------------------------------

any tips? thanks a lot!

**Comment by prashantsinhpvips** [comment]
@peyo-hd Is this issue is fixed? I am still facing the same issue in arpi-10 branch.
It is getting reboot after sometime.
