### ISSUE TITLE
Default license

### ISSUE THREAD

**Issue by kaushal98** [android-rpi/device_arpi_rpi4#33]
Hi, can you please add a default license to this repo and also for [local_manifests repo](https://github.com/android-rpi/local_manifests) ?  

Github public repos w/o any default license are effectively `no license granted`

https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

Thanks

**Comment by peyo-hd** [comment]
Hi kaushal,

Apache license is included in rpi4.mk and BoardConfig.mk which are main part of this makefile project.
Other files are mostly copied from AOSP sources. Then keeping original license.

In the docs link, default right for github users are defined. I will keep local_manifests under this default condition.
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

**Comment by kaushal98** [comment]
Thanks @peyo-hd
