### ISSUE TITLE
Support for Tablet mode

### ISSUE THREAD

**Issue by lohriialo** [android-rpi/device_arpi_rpi4#35]
@peyo-hd is there any plan to add support for tablet mode device tree branch? TV mode has some touch/input/navigations issues when trying to use in real world application on a touch screen when there's no physical keyboard

A tablet mode branch for either arpi-10 or arpi-11 would be a really good addition

**Comment by Road-Drum** [comment]
you can change the following to tablet counterpart

```
$(call inherit-product, device/google/atv/products/atv_base.mk)
...
PRODUCT_AAPT_PREF_CONFIG := tvdpi
PRODUCT_CHARACTERISTICS := tv
```

refer to older @KonstaT source code of lineage-rpi

it's probably just me but idk why `TARGET_SUPPORTS_32_BIT_APPS := false`. hopefully @peyo-hd can explain it better since android r came with native bridge support that translates ARM instruction

**Comment by lohriialo** [comment]
`lineage-rpi` does a bunch of customisations unlike `android-rpi` which is stock, would be really good to have an official tablet device branch in `android-rpi` which can be very helpful for anyone learning `android-rpi`

`lineage-rpi` : 
```
$(call inherit-product, vendor/lineage/config/common_full_tablet_wifionly.mk)
...
$(call inherit-product, $(SRC_TARGET_DIR)/product/full_base.mk)
$(call inherit-product, $(SRC_TARGET_DIR)/product/go_defaults.mk)
$(call inherit-product, frameworks/native/build/tablet-7in-hdpi-1024-dalvik-heap.mk)
$(call inherit-product, vendor/brcm/rpi3/rpi3-vendor.mk)
...
PRODUCT_AAPT_PREF_CONFIG := mdpi
PRODUCT_CHARACTERISTICS := tablet
```

**Comment by lohriialo** [comment]
I've tried @hkoosha tablet mode https://github.com/hkoosha/device_arpi_rpi4 but it doesn't boot and this branch is many commits behind `android-rpi`

**Comment by peyo-hd** [comment]
Currently, no plan of tablet profile on this repo.
Someone could maintain it on forked branch.

**Comment by Road-Drum** [comment]
@peyo-hd that's okay. anyway can you give an explanation why 32 bit app support is disabled given that there are quite a lot of them and arm64 devices doesn't have problem running arm apps?

**Comment by peyo-hd** [comment]
arm 32bit enable with following commit :
https://github.com/android-rpi/device_arpi_rpi4/commit/b77892dba66ebbe0f6814427a393d344cf1c314e

**Comment by lohriialo** [comment]
Tablet mode https://github.com/lohriialo/device_arpi_rpi4/tree/arpi-10-tablet

Settings UI back button doesn't work, not sure why...

**Comment by lohriialo** [comment]
re-synced code base and rebuilt, back button is now working

**Comment by andersling** [comment]
@lohriialo HI,Sir! Do you have plan to move this andorid-rpi 11 to Tablet mode? Thanks for your greate job on andorid-rpi 10 tablet mode!~
