### ISSUE TITLE
WIFI/BT doesn't work

### ISSUE THREAD

**Issue by wildpig1979** [android-rpi/device_arpi_rpi4#4]
Hello ARPI Team,
      I followed the steps on README under /device/arpi/rpi4 folder on Android 10 and it could run normally on RPI 4 .  But WIFI/BT doesn't work. I could see wpa_supplicant service was not started. Besides, /dev/socket/wpa_wlan0  and /dev/rfkill was not actuallly created. I could see WIFI firmware under /root/lib/firmware/brcm .  Can you give some suggestions to me ? Is there anything wrong ?

**Comment by peyo-hd** [comment]
Wifi/BT is not supported yet.
Waiting for contribution on it.

**Comment by wildpig1979** [comment]
Hi Peyo,
     Thank you  for your timely reply.  Looking forward to your contribution.

**Comment by saurabhin25** [comment]
Is there any downloadble image

**Comment by ghost** [comment]
No, there is **no** downloadable image!!! Our image will be ready soon, which is based on this repo
