### ISSUE TITLE
Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

### ISSUE THREAD

**Issue by Aniketh01** [android-rpi/device_arpi_rpi4#76]
When I try to install apps through adb, I get an error like this: adb: failed to install app.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]. What is the root cause of this error? How can I fix this?

**Comment by peyo-hd** [comment]
arpi-11, arpi-12 builds are supporting Arm 64bit ABI only.

**Comment by Aniketh01** [comment]
Thanks for the response. Is there any commits or references that I can follow to add multi ABI support?

**Comment by peyo-hd** [comment]
https://github.com/android-rpi/device_arpi_rpi4/commit/fe2c6e7a42fde5ed95344636cbaeb839aa953db4
But there might be issues.

**Comment by Aniketh01** [comment]
Can you please elaborate a bit more? What sort of issues might I face?

**Comment by Aniketh01** [comment]
Have you tested AOSP 11 for 32 bit ABI alone without multilib support? Does it work well?
